print("Welcome to multiplication/Exponent table app")
name=input(print("Hello, What is your name: "))
no=float(input(print("What number would you like to work with")))

print(f"Multiplication table for {no}")
print(f"\t1.0 * {no} = {round(1.0*no,4)} ")
print(f"\t2.0 * {no} = {round(2.0*no,4)} ")
print(f"\t3.0 * {no} = {round(3.0*no,4)} ")
print(f"\t4.0 * {no} = {round(4.0*no,4)} ")
print(f"\t5.0 * {no} = {round(5.0*no,4)} ")
print(f"\t6.0 * {no} = {round(6.0*no,4)} ")
print(f"\t7.0 * {no} = {round(7.0*no,4)} ")
print(f"\t8.0 * {no} = {round(8.0*no,4)} ")
print(f"\t9.0 * {no} = {round(9.0*no,4)} ")
print(f"\t10.0 * {no} = {round(10.0*no,4)} ")

print(f"Exponent table for {no} is")
print(f"\t{no} * * 1.0 = {round(no**1.0,4)}")
print(f"\t{no} * * 2.0 = {round(no**2.0,4)}")
print(f"\t{no} * * 3.0 = {round(no**3.0,4)}")
print(f"\t{no} * * 4.0 = {round(no**4.0,4)}")
print(f"\t{no} * * 5.0 = {round(no**5.0,4)}")
print(f"\t{no} * * 6.0 = {round(no**6.0,4)}")
print(f"\t{no} * * 7.0 = {round(no**7.0,4)}")
print(f"\t{no} * * 8.0 = {round(no**8.0,4)}")
print(f"\t{no} * * 9.0 = {round(no**9.0,4)}")
print(f"\t{no} * * 10.0 = {round(no**10.0,4)}")

